---
title: "Sparplan der Kids 2021"
date: "Letztes Update: `r format(Sys.time(), '%d.%m.%Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(readxl)
library(tidyverse)
library(scales)

# library(xts)
# library(lubridate)
# library(stringr)
# library(data.table)
library(gameofthrones) ## farbpaletten
# library(DT)
# library(gt)

library(tidyquant)
library(directlabels)
```

```{r}

Sparplan_Doku_Emil <- read_excel("~/Documents/Deutsche_Bank_u_VB/Sparplan_Doku.xlsx", 
    sheet = "Emil_R", col_types = c("date", 
        "numeric", "numeric", "numeric", "numeric", "numeric"))


Sparplan_Doku_Emil <- Sparplan_Doku_Emil %>%
  mutate(Prozent = round((Gesamt/Ansparen-1)*100,1)) %>%
  filter(Closing >= "2021-01-01" & Closing <= "2022-01-01")
```

```{r}
pal <- got(3, option = "Daenerys", direction = -1)

ggplot(Sparplan_Doku_Emil, aes(x=Closing))+
  geom_ribbon(aes(ymin=Ansparen, ymax=Gesamt,fill="Rendite"), alpha=0.8)+
  geom_point(aes(y=Gesamt),alpha=.8,shape=4)+
  
  geom_area(aes(y=Ansparen, fill="Ansparen"), alpha=.8)+
  geom_point(aes(y=Ansparen),alpha=.8, shape=4)+
  geom_text(aes(y=Ansparen, label=paste0(Ansparen, " €")),hjust=0.5, vjust=2, alpha=.8, size = 3)+
  
  geom_text(aes(y=Gesamt, label=paste0(Gesamt," €\n", Prozent, "%")),hjust=0.5, vjust=-0.5, alpha=.8, size = 3)+
  
  labs(title="Sparplan Emil", x="", y="", fill="")+
  scale_y_continuous(limits = c(0, max(Sparplan_Doku_Emil$Gesamt)+2000), labels = dollar_format(suffix = " €", prefix = ""))+
  scale_x_datetime( expand = c(0.08, 0),labels = date_format("%b %y"), breaks = "1 month")+
  theme_classic()+
  theme(legend.position = c(0.7, 0.2),
          legend.direction = "horizontal")+
  scale_fill_manual(values=pal)
```


```{r}

Sparplan_Doku_Alva <- read_excel("~/Documents/Deutsche_Bank_u_VB/Sparplan_Doku.xlsx", 
    sheet = "Alva_R", col_types = c("date", 
        "numeric", "numeric", "numeric"))

Sparplan_Doku_Alva <- Sparplan_Doku_Alva %>%
  mutate(Rendite = ETFs - Ansparen) %>%
  mutate(Prozent = round(Rendite/Ansparen*100,1)) %>%
  filter(Closing >= "2021-01-01" & Closing <= "2022-01-01") 

# %>%
#   mutate(Closing = Closing - days(20))
```

```{r}
# Daten visualisieren

ggplot(Sparplan_Doku_Alva, aes(x=Closing))+
  geom_ribbon(aes(ymin=Ansparen, ymax=ETFs,fill="Rendite"), alpha=0.8)+
  geom_point(aes(y=ETFs),alpha=.8,shape=4)+
  geom_text(aes(y=ETFs, label=paste0(ETFs," €\n ", Prozent, "%")),hjust=0.5, vjust=-0.5, alpha=.8, size = 3)+
  geom_area(aes(y=Ansparen, fill="Ansparen"), alpha=.8)+
  geom_point(aes(y=Ansparen),alpha=.8, shape=4)+
  geom_text(aes(y=Ansparen, label=Ansparen),hjust=0.5, vjust=2, alpha=.8, size = 3)+
  labs(title="Sparplan Alva", x="", y="", fill="")+
  scale_y_continuous(limits = c(0, 10000), labels = dollar_format(suffix = " €", prefix = ""))+
  scale_x_datetime( expand = c(0.08,0),labels = date_format("%b %y"), breaks = "1 month")+
  theme_classic()+
  theme(legend.position = c(0.7, 0.1),
          legend.direction = "horizontal")+
  scale_fill_manual(values=pal)
#  theme(legend.position="bottom")
```
