---
title: "SUBHH"
author: "JT"
date: "1/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(scales)

library(plotly)
library(xts)
library(ggrepel)

library(highcharter)
library(tidyquant)
library(directlabels)
```



```{r}
Besuche <- read_excel("~/Dropbox/Bewerbungen/2020_11_SUB Hamburg/Dokumente/Daten.xlsx", sheet = "Besuche_Entleihungen")
```

```{r}
Besuche <- Besuche %>%
  mutate(pct_change_d_cumsum = (Downloads/Downloads[1]-1)*100) %>%
  mutate(pct_change_e_cumsum = (Entleihungen/Entleihungen[1]-1)*100)%>%
  mutate(pct_change_b_cumsum = (Besuche/Besuche[1]-1)*100)
```


```{r}
# falsche Berechnung
Besuche <- Besuche %>%
  mutate(pct_change_b = (Besuche/lag(Besuche) - 1) * 100)%>%
  replace_na(list(pct_change_b = 0)) %>%
  mutate(pct_change_b_cumsum = cumsum(pct_change_b)) %>%
  mutate(pct_change_e = (Entleihungen/lag(Entleihungen) - 1) * 100)%>%
  replace_na(list(pct_change_e = 0)) %>%
  mutate(pct_change_e_cumsum = cumsum(pct_change_e)) %>%
  mutate(pct_change_d = (Downloads/lag(Downloads) - 1) * 100)%>%
  replace_na(list(pct_change_d = 0)) %>%
  mutate(pct_change_d_cumsum = cumsum(pct_change_d)) %>%
  mutate(pct_change = (Downloads/Downloads[1]-1)*100) %>%
  mutate(pct_change_ent = (Entleihungen/Entleihungen[1]-1)*100)%>%
  mutate(pct_change_bes = (Besuche/Besuche[1]-1)*100)
```

```{r}
ggplot(data=Besuche, aes(x=Jahr))+
#  geom_line(aes(y=pct_change_b_cumsum, color="Besuche"), size =2, alpha = 0.8)+
  geom_line(aes(y=pct_change_e_cumsum, color = "Ausleihen"), size =2, alpha = 0.5)+
  geom_text(aes(y=pct_change_e_cumsum, label=paste0(round(pct_change_e_cumsum,0), " %")), alpha=.8)+
#  geom_text(aes(y=pct_change_b_cumsum, label=round(pct_change_b,0)), alpha=.8)+
  geom_line(y=0, linetype = "dashed", alpha=.8)+
  labs(title="Ausleihen", subtitle ="Prozentuale Veränderung 2012 bis 2019", color = "", x = "", y = "", caption = "Daten aus Bibliotheksstatistik
des Bibliothekssystems Universität Hamburg")+
  theme_classic()+
  scale_y_continuous(limits = c(NA, 10), labels = dollar_format(suffix = " %", prefix = ""))+
  scale_x_datetime(labels = date_format("%Y"), breaks = "1 year")+
  theme(legend.position = c(0.3,0.3))+
  scale_color_brewer(palette="Set1")
  

```


```{r}
ggplot(data=Besuche, aes(x=Jahr))+
  geom_line(aes(y=pct_change_b_cumsum, color="Besuche"), size =2, alpha = 0.5)+
  geom_line(aes(y=pct_change_e_cumsum, color = "Ausleihen"), size =2, alpha = 0.5)+
  geom_text(aes(y=pct_change_e_cumsum, label=paste0(round(pct_change_e_cumsum,0), " %")), alpha=.8)+
  geom_text(aes(y=pct_change_b_cumsum, label=paste0(round(pct_change_b_cumsum,0), " %")), alpha=.8)+
  geom_line(y=0, linetype = "dashed", alpha=.8)+
  labs(title="Ausleihen und Besuche", subtitle ="Prozentuale Veränderung 2012 bis 2019", color = "", x = "", y = "", caption = "Daten aus Bibliotheksstatistik
des Bibliothekssystems Universität Hamburg")+
  theme_classic()+
  scale_y_continuous(limits = c(NA, 10), labels = dollar_format(suffix = " %", prefix = ""))+
  scale_x_datetime(labels = date_format("%Y"), breaks = "1 year")+
  theme(legend.position = c(0.3,0.3))+
  scale_color_brewer(palette="Set1")
  

```

```{r}
ggplot(data=Besuche, aes(x=Jahr))+
  geom_line(aes(y=pct_change_b_cumsum, color="Besuche"), size =2, alpha = 0.5)+
  geom_line(aes(y=pct_change_e_cumsum, color = "Ausleihen"), size =2, alpha = 0.5)+
  geom_line(aes(y=pct_change_d_cumsum, color = "Downloads aus E-Books"), size =2, alpha = 0.5)+
  geom_text(aes(y=pct_change_e_cumsum, label=paste0(round(pct_change_e_cumsum,0), " %")), alpha=.8)+
  geom_text(aes(y=pct_change_b_cumsum, label=paste0(round(pct_change_b_cumsum,0), " %")), alpha=.8)+
  geom_text(aes(y=pct_change_d_cumsum, label=paste0(round(pct_change_d_cumsum,0), " %")), alpha=.8)+
  geom_line(y=0, linetype = "dashed", alpha=.8)+
  labs(title="Ausleihen, Besuche und Downloads aus E-Books", subtitle ="Prozentuale Veränderung 2012 bis 2019", color = "", x = "", y = "", caption = "Daten aus Bibliotheksstatistik 
       des Bibliothekssystems Universität Hamburg (Ausleihen und Besuche)
       und Simulation (Downloads aus E-Books)" )+
  theme_classic()+
  scale_y_continuous(limits = c(NA, NA), labels = dollar_format(suffix = " %", prefix = ""))+
  scale_x_datetime(labels = date_format("%Y"), breaks = "1 year")+
  theme(legend.position = c(0.2,0.8))+
  scale_color_brewer(palette="Set1")
  

```